//! Shell completion script generation.
//!
//! `clap_complete` handles the structural completions (subcommands, flags).
//! This module enhances those scripts with completions for the proxy layer —
//! the known command families sift filters (git, xcodebuild, swift, etc.).

use clap_complete::Shell;
use std::io::Write;

/// Known top-level commands that sift can filter, with short descriptions.
const PROXY_COMMANDS: &[(&str, &str)] = &[
    ("git", "Run git with smart output filtering"),
    ("xcodebuild", "Run xcodebuild with smart output filtering"),
    ("swift", "Run swift build/test with smart output filtering"),
    ("xcrun", "Run xcrun simctl with smart output filtering"),
    ("swiftlint", "Run swiftlint with smart output filtering"),
    ("swiftformat", "Run swiftformat with smart output filtering"),
    ("fastlane", "Run fastlane with smart output filtering"),
    ("pod", "Run CocoaPods with smart output filtering"),
    ("tuist", "Run tuist with smart output filtering"),
    ("curl", "Run curl with smart output filtering"),
    ("grep", "Run grep/rg with smart output filtering"),
    ("rg", "Run ripgrep with smart output filtering"),
    ("cat", "Run cat with smart output filtering"),
    ("ls", "Run ls with smart output filtering"),
    ("find", "Run find with smart output filtering"),
    ("codesign", "Run codesign with smart output filtering"),
    (
        "security",
        "Run security find-identity with smart output filtering",
    ),
    ("agvtool", "Run agvtool with smart output filtering"),
    (
        "xcode-select",
        "Run xcode-select with smart output filtering",
    ),
    (
        "xcresulttool",
        "Run xcresulttool with smart output filtering",
    ),
    ("docc", "Run docc with smart output filtering"),
];

/// Generate a completion script for the given shell and write it to `out`.
///
/// Uses `clap_complete::generate` for the structural completions (flags,
/// subcommands), then appends enhanced proxy-command completions on top.
pub fn generate(shell: Shell, cmd: &mut clap::Command, out: &mut dyn Write) {
    match shell {
        Shell::Zsh => write_zsh(out),
        Shell::Bash => write_bash(out),
        Shell::Fish => write_fish(out),
        other => {
            // Fall back to clap_complete for other shells
            clap_complete::generate(other, cmd, "sift", out);
        }
    }
}

// ── zsh ───────────────────────────────────────────────────────────────────────

fn write_zsh(out: &mut dyn Write) {
    let proxy_completions = zsh_proxy_completions();
    let script = format!(
        r#"#compdef sift
# sift shell completions for zsh
# Generated by `sift completions zsh`
# Add to your .zshrc: source <(sift completions zsh)
# Or copy to your completions dir: sift completions zsh > ~/.zsh/completions/_sift

_sift() {{
    local context state line
    typeset -A opt_args

    _arguments -C \
        '(-v)-v[Increase verbosity (-v, -vv, -vvv)]' \
        '--raw[Pass through raw output without filtering]' \
        '--json[Output structured JSON]' \
        '--stream[Stream output progressively for long-running commands]' \
        '1: :_sift_cmds' \
        '*:: :->args'

    case $state in
        args)
            case $words[1] in
                stats)       _sift_stats ;;
                init)        _sift_init ;;
                completions) _sift_completions_shell ;;
                git)         _sift_git ;;
                xcodebuild)  _sift_xcodebuild ;;
                swift)       _sift_swift ;;
                xcrun)       _sift_xcrun ;;
                pod)         _sift_pod ;;
                tuist)       _sift_tuist ;;
                docc)        _sift_docc ;;
                agvtool)     _sift_agvtool ;;
                security)    _sift_security ;;
                *)           _default ;;
            esac
            ;;
    esac
}}

_sift_cmds() {{
    local -a cmds
    cmds=(
        'stats:Show output reduction statistics'
        'init:Install or manage sift shell hooks and AI agent instructions'
        'completions:Generate shell completion scripts'
{proxy_entries}    )
    _describe 'sift commands' cmds
}}

_sift_stats() {{
    _arguments \
        '--all[Include all historical statistics]' \
        '--reset[Clear all historical statistics]' \
        '--json[Output statistics as JSON]' \
        '--last[Show only the last N invocations]:N:'
}}

_sift_init() {{
    _arguments \
        '--shell[Install shell hooks into ~/.zshrc / ~/.bashrc]' \
        '--commands[Comma-separated commands to wrap (git,xcodebuild,...)]:cmds:' \
        '--claude[Create/update CLAUDE.md with sift instructions]' \
        '--copilot[Create/update .github/copilot-instructions.md]' \
        '--xcode-project[Write Xcode project-specific context to CLAUDE.md]' \
        '--show[Show current installation status]' \
        '--uninstall[Remove all sift hooks and instruction files]'
}}

_sift_completions_shell() {{
    local -a shells
    shells=('bash:Bash shell' 'zsh:Zsh shell' 'fish:Fish shell' 'elvish:Elvish shell' 'powershell:PowerShell')
    _describe 'shell' shells
}}

_sift_git() {{
    local -a subcommands
    subcommands=(
        'status:Show working tree status'
        'diff:Show changes'
        'log:Show commit log'
        'log --graph:Show commit graph'
    )
    _describe 'git subcommands' subcommands
}}

_sift_xcodebuild() {{
    local -a subcommands
    subcommands=(
        'build:Build a target or scheme'
        'test:Run tests'
        'archive:Archive a scheme'
        '-list:List schemes, targets and configurations'
        '-showBuildSettings:Show build settings'
    )
    _describe 'xcodebuild subcommands' subcommands
}}

_sift_swift() {{
    local -a subcommands
    subcommands=(
        'build:Build the Swift package'
        'test:Run Swift package tests'
        'package resolve:Resolve package dependencies'
        'package update:Update package dependencies'
        'package show-dependencies:Show dependency tree'
    )
    _describe 'swift subcommands' subcommands
}}

_sift_xcrun() {{
    local -a subcommands
    subcommands=(
        'simctl list:List available simulators'
        'simctl boot:Boot a simulator'
        'simctl install:Install an app on a simulator'
        'simctl launch:Launch an app on a simulator'
        'simctl erase:Erase a simulator'
        'simctl delete:Delete a simulator'
    )
    _describe 'xcrun subcommands' subcommands
}}

_sift_pod() {{
    local -a subcommands
    subcommands=('install:Install pods' 'update:Update pods')
    _describe 'pod subcommands' subcommands
}}

_sift_tuist() {{
    local -a subcommands
    subcommands=('generate:Generate Xcode project' 'fetch:Fetch dependencies' 'cache:Cache dependencies')
    _describe 'tuist subcommands' subcommands
}}

_sift_docc() {{
    local -a subcommands
    subcommands=('convert:Convert documentation' 'preview:Preview documentation')
    _describe 'docc subcommands' subcommands
}}

_sift_agvtool() {{
    local -a subcommands
    subcommands=('what-version:Print current version' 'new-version:Set a new version' 'bump-versions:Bump version number')
    _describe 'agvtool subcommands' subcommands
}}

_sift_security() {{
    local -a subcommands
    subcommands=('find-identity:List available signing identities')
    _describe 'security subcommands' subcommands
}}

_sift "$@"
"#,
        proxy_entries = proxy_completions,
    );
    let _ = out.write_all(script.as_bytes());
}

fn zsh_proxy_completions() -> String {
    PROXY_COMMANDS
        .iter()
        .map(|(cmd, desc)| format!("        '{cmd}:{desc}'\n"))
        .collect()
}

// ── bash ──────────────────────────────────────────────────────────────────────

fn write_bash(out: &mut dyn Write) {
    let proxy_cmds: Vec<&str> = PROXY_COMMANDS.iter().map(|(c, _)| *c).collect();
    let proxy_list = proxy_cmds.join(" ");

    let script = format!(
        r#"# sift shell completions for bash
# Generated by `sift completions bash`
# Add to your .bashrc: source <(sift completions bash)
# Or copy: sift completions bash > /usr/local/etc/bash_completion.d/sift

_sift_completions() {{
    local cur prev words cword
    _init_completion 2>/dev/null || {{
        COMPREPLY=()
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    }}

    local global_flags="--raw --json --stream -v -vv -vvv"
    local subcommands="stats init completions {proxy_list}"

    # Complete first argument
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=($(compgen -W "$subcommands $global_flags" -- "$cur"))
        return
    fi

    local cmd="${{COMP_WORDS[1]}}"

    case "$cmd" in
        stats)
            COMPREPLY=($(compgen -W "--all --reset --json --last" -- "$cur"))
            ;;
        init)
            COMPREPLY=($(compgen -W "--shell --commands --claude --copilot --xcode-project --show --uninstall" -- "$cur"))
            ;;
        completions)
            COMPREPLY=($(compgen -W "bash zsh fish elvish powershell" -- "$cur"))
            ;;
        git)
            COMPREPLY=($(compgen -W "status diff log" -- "$cur"))
            ;;
        xcodebuild)
            COMPREPLY=($(compgen -W "build test archive -list -showBuildSettings" -- "$cur"))
            ;;
        swift)
            if [[ $COMP_CWORD -eq 2 ]]; then
                COMPREPLY=($(compgen -W "build test package" -- "$cur"))
            elif [[ "${{COMP_WORDS[2]}}" == "package" ]]; then
                COMPREPLY=($(compgen -W "resolve update show-dependencies" -- "$cur"))
            fi
            ;;
        xcrun)
            if [[ $COMP_CWORD -eq 2 ]]; then
                COMPREPLY=($(compgen -W "simctl" -- "$cur"))
            elif [[ "${{COMP_WORDS[2]}}" == "simctl" ]]; then
                COMPREPLY=($(compgen -W "list boot install launch erase delete" -- "$cur"))
            fi
            ;;
        pod)
            COMPREPLY=($(compgen -W "install update" -- "$cur"))
            ;;
        tuist)
            COMPREPLY=($(compgen -W "generate fetch cache" -- "$cur"))
            ;;
        docc)
            COMPREPLY=($(compgen -W "convert preview" -- "$cur"))
            ;;
        agvtool)
            COMPREPLY=($(compgen -W "what-version new-version bump-versions" -- "$cur"))
            ;;
        security)
            COMPREPLY=($(compgen -W "find-identity" -- "$cur"))
            ;;
        *)
            COMPREPLY=($(compgen -f -- "$cur"))
            ;;
    esac
}}

complete -F _sift_completions sift
"#,
        proxy_list = proxy_list,
    );
    let _ = out.write_all(script.as_bytes());
}

// ── fish ──────────────────────────────────────────────────────────────────────

fn write_fish(out: &mut dyn Write) {
    let mut lines: Vec<String> = vec![
        "# sift shell completions for fish".into(),
        "# Generated by `sift completions fish`".into(),
        "# Copy to: sift completions fish > ~/.config/fish/completions/sift.fish".into(),
        String::new(),
        "# Disable file completions for sift itself".into(),
        "complete -c sift -f".into(),
        String::new(),
        "# Global flags".into(),
        "complete -c sift -n '__fish_use_subcommand' -l raw   -d 'Pass through raw output'".into(),
        "complete -c sift -n '__fish_use_subcommand' -l json  -d 'Output structured JSON'".into(),
        "complete -c sift -n '__fish_use_subcommand' -l stream -d 'Stream output progressively'".into(),
        "complete -c sift -n '__fish_use_subcommand' -s v     -d 'Increase verbosity'".into(),
        String::new(),
        "# Subcommands".into(),
        "complete -c sift -n '__fish_use_subcommand' -a stats       -d 'Show output reduction statistics'".into(),
        "complete -c sift -n '__fish_use_subcommand' -a init        -d 'Install or manage sift shell hooks'".into(),
        "complete -c sift -n '__fish_use_subcommand' -a completions -d 'Generate shell completion scripts'".into(),
    ];

    lines.push(String::new());
    lines.push("# Proxy commands".into());
    for (cmd, desc) in PROXY_COMMANDS {
        lines.push(format!(
            "complete -c sift -n '__fish_use_subcommand' -a {cmd} -d '{desc}'"
        ));
    }

    lines.push(String::new());
    lines.push("# stats flags".into());
    for (flag, desc) in &[
        ("all", "Include all historical statistics"),
        ("reset", "Clear all historical statistics"),
        ("json", "Output statistics as JSON"),
        ("last", "Show only the last N invocations"),
    ] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from stats' -l {flag} -d '{desc}'"
        ));
    }

    lines.push(String::new());
    lines.push("# init flags".into());
    for (flag, desc) in &[
        ("shell", "Install shell hooks"),
        ("commands", "Comma-separated commands to wrap"),
        ("claude", "Create/update CLAUDE.md"),
        ("copilot", "Create/update copilot-instructions.md"),
        ("xcode-project", "Write Xcode project context"),
        ("show", "Show installation status"),
        ("uninstall", "Remove all sift hooks"),
    ] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from init' -l {flag} -d '{desc}'"
        ));
    }

    lines.push(String::new());
    lines.push("# completions: shell choices".into());
    for shell in &["bash", "zsh", "fish", "elvish", "powershell"] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from completions' -a {shell}"
        ));
    }

    lines.push(String::new());
    lines.push("# git subcommands".into());
    for sub in &["status", "diff", "log"] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from git' -a {sub}"
        ));
    }

    lines.push(String::new());
    lines.push("# xcodebuild subcommands".into());
    for (sub, desc) in &[
        ("build", "Build a target or scheme"),
        ("test", "Run tests"),
        ("archive", "Archive a scheme"),
        ("-list", "List schemes, targets and configurations"),
        ("-showBuildSettings", "Show build settings"),
    ] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from xcodebuild' -a '{sub}' -d '{desc}'"
        ));
    }

    lines.push(String::new());
    lines.push("# swift subcommands".into());
    for sub in &["build", "test", "package"] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from swift' -a {sub}"
        ));
    }

    lines.push(String::new());
    lines.push("# xcrun simctl subcommands".into());
    for sub in &["list", "boot", "install", "launch", "erase", "delete"] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from xcrun' -a 'simctl {sub}'"
        ));
    }

    lines.push(String::new());
    lines.push("# pod subcommands".into());
    for sub in &["install", "update"] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from pod' -a {sub}"
        ));
    }

    lines.push(String::new());
    lines.push("# tuist subcommands".into());
    for sub in &["generate", "fetch", "cache"] {
        lines.push(format!(
            "complete -c sift -n '__fish_seen_subcommand_from tuist' -a {sub}"
        ));
    }

    let script = lines.join("\n") + "\n";
    let _ = out.write_all(script.as_bytes());
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_to_string(shell: Shell) -> String {
        let mut cmd = crate::cli::Cli::command();
        let mut buf = Vec::new();
        generate(shell, &mut cmd, &mut buf);
        String::from_utf8(buf).expect("completion output is valid UTF-8")
    }

    #[test]
    fn zsh_completions_contain_sift_function() {
        let out = generate_to_string(Shell::Zsh);
        assert!(out.contains("#compdef sift"));
        assert!(out.contains("_sift()"));
    }

    #[test]
    fn zsh_completions_contain_proxy_commands() {
        let out = generate_to_string(Shell::Zsh);
        assert!(out.contains("xcodebuild"));
        assert!(out.contains("swiftlint"));
        assert!(out.contains("fastlane"));
    }

    #[test]
    fn zsh_completions_contain_subcommand_handlers() {
        let out = generate_to_string(Shell::Zsh);
        assert!(out.contains("_sift_stats"));
        assert!(out.contains("_sift_init"));
        assert!(out.contains("_sift_xcodebuild"));
        assert!(out.contains("_sift_git"));
    }

    #[test]
    fn zsh_completions_contain_global_flags() {
        let out = generate_to_string(Shell::Zsh);
        assert!(out.contains("--raw"));
        assert!(out.contains("--json"));
        assert!(out.contains("--stream"));
    }

    #[test]
    fn bash_completions_contain_complete_directive() {
        let out = generate_to_string(Shell::Bash);
        assert!(out.contains("complete -F _sift_completions sift"));
    }

    #[test]
    fn bash_completions_contain_proxy_commands() {
        let out = generate_to_string(Shell::Bash);
        assert!(out.contains("xcodebuild"));
        assert!(out.contains("fastlane"));
        assert!(out.contains("swiftlint"));
    }

    #[test]
    fn bash_completions_contain_subcommand_cases() {
        let out = generate_to_string(Shell::Bash);
        assert!(out.contains("stats)"));
        assert!(out.contains("xcodebuild)"));
        assert!(out.contains("git)"));
    }

    #[test]
    fn fish_completions_contain_complete_directives() {
        let out = generate_to_string(Shell::Fish);
        assert!(out.contains("complete -c sift"));
        assert!(out.contains("__fish_use_subcommand"));
    }

    #[test]
    fn fish_completions_contain_proxy_commands() {
        let out = generate_to_string(Shell::Fish);
        assert!(out.contains("xcodebuild"));
        assert!(out.contains("swiftlint"));
        assert!(out.contains("fastlane"));
    }

    #[test]
    fn fish_completions_contain_subcommand_completions() {
        let out = generate_to_string(Shell::Fish);
        assert!(out.contains("__fish_seen_subcommand_from stats"));
        assert!(out.contains("__fish_seen_subcommand_from init"));
        assert!(out.contains("__fish_seen_subcommand_from xcodebuild"));
    }

    #[test]
    fn all_proxy_commands_in_zsh() {
        let out = generate_to_string(Shell::Zsh);
        for (cmd, _) in PROXY_COMMANDS {
            assert!(out.contains(cmd), "missing proxy command in zsh: {cmd}");
        }
    }

    #[test]
    fn all_proxy_commands_in_bash() {
        let out = generate_to_string(Shell::Bash);
        for (cmd, _) in PROXY_COMMANDS {
            assert!(out.contains(cmd), "missing proxy command in bash: {cmd}");
        }
    }

    #[test]
    fn all_proxy_commands_in_fish() {
        let out = generate_to_string(Shell::Fish);
        for (cmd, _) in PROXY_COMMANDS {
            assert!(out.contains(cmd), "missing proxy command in fish: {cmd}");
        }
    }
}
